chore(RHTAPWATCH-564): Run exporter service Go unit tests for each PR opened
redhat-appstudio/o11y pull request #113
Opened 2023-11-15 19:11 UTC by Kousalya1998

- Add a new GH actions workflow that runs the GO unit tests on each opened pull request.

2023-11-15 19:43 UTC, amisstea commented on .github/workflows/unit_tests.yaml
> +      image: registry.access.redhat.com/ubi8/go-toolset:1.19.13-2.1698062273
Shouldn't we be using go 1.20.10+ at this point to mitigate CVE-2023-44487? See [RHTAPWATCH-546](https://issues.redhat.com/browse/RHTAPWATCH-546) which predated this new exporter. cc @hmariset

2023-11-15 19:46 UTC, hmariset commented on .github/workflows/unit_tests.yaml
> +      image: registry.access.redhat.com/ubi8/go-toolset:1.19.13-2.1698062273
yes, `registry.access.redhat.com/ubi9/go-toolset:1.20.10-2` is the image we are using now in segment-bridge

2023-11-15 20:23 UTC, Kousalya1998 commented on .github/workflows/unit_tests.yaml
> +      image: registry.access.redhat.com/ubi8/go-toolset:1.19.13-2.1698062273
Updated

2023-11-16 08:26 UTC, Omeramsc requested changes
Isn't Tekton being mostly used in the o11y repo?

2023-11-16 08:26 UTC, Omeramsc commented on .github/workflows/unit_tests.yaml
> +          https://github.com/stedolan/jq/releases/download/jq-1.7/jq-linux64 \
Is there a need of jq in this repo's unit tests?

2023-11-16 08:28 UTC, yftacherzog commented
> Isn't Tekton being mostly used in the o11y repo?

I'd also prefer we stick with tekton unless we have a compelling reason for introducing another flow. The ticket was also mentioning tekton for that reason.

2023-11-16 15:37 UTC, Kousalya1998 commented
> Isn't Tekton being mostly used in the o11y repo?

With Go unit tests, I followed the same approach as segment-bridge and used GitHub actions. If o11y uses only tekton then it makes sense to have only tekton.

2023-11-17 18:57 UTC, amisstea approved these changes

2023-11-17 18:59 UTC, Kousalya1998 commented
/retest

2023-11-17 19:11 UTC, hmariset commented
LGTM

2023-11-17 19:11 UTC, hmariset approved these changes

2023-11-17 20:03 UTC, amisstea approved these changes

2023-11-17 20:04 UTC, amisstea commented
@Omeramsc's concern was addressed. Merging this.

2023-11-17 20:04 UTC, merged

2023-11-19 07:25 UTC, yftacherzog commented
/test