Disable component alerts
redhat-appstudio/o11y pull request #251
Opened 2024-04-10 13:40 UTC by johnmcollier

- Comments out the Component alerts until https://issues.redhat.com/browse/DEVHAS-641 has been completed and we've had a chance to re-evaluate their position within HAS

2024-04-10 13:45 UTC, avi-biton commented
We should also remove the tests for these alerts from https://github.com/redhat-appstudio/o11y/tree/main/test/promql/tests/data_plane

2024-04-10 13:46 UTC, johnmcollier commented
@avi-biton Thanks, yup. Just realized I missed those too, so I've updated the PR to remove them

2024-04-10 13:55 UTC, amisstea approved these changes
LGTM

2024-04-10 13:57 UTC, avi-biton commented
I think it will fail as we are trying to refer to the alerts in our make file and it is not a `PrometheusRule` object.
It might be that we will need to remove it completely

2024-04-10 13:57 UTC, yftacherzog requested changes

2024-04-10 14:01 UTC, avi-biton commented on rhobs/alerting/data_plane/prometheus.component_alerts.yaml
@johnmcollier 
Indeed, tested locally and failed.
These files has to be removed completely

2024-04-10 14:05 UTC, johnmcollier commented on rhobs/alerting/data_plane/prometheus.component_alerts.yaml
Ah, that's too bad. Was hoping we could just comment them out.

In that case, I'll update the PR to remove them

2024-04-10 14:11 UTC, avi-biton commented
lgtm

2024-04-10 14:12 UTC, avi-biton approved these changes

2024-04-10 16:54 UTC, yftacherzog approved these changes

2024-04-11 07:10 UTC, yftacherzog approved these changes

2024-04-11 07:10 UTC, merged